### ISSUE TITLE
missing "latest" tag

### ISSUE THREAD

**Issue by BrannonKing** [utensils/docker-darling#1]
Can you tag this image on Docker hub with "latest" ? Maybe update it to latest code too? Thanks.

**Comment by qaisjp** [comment]
Please @jamesbrink!

**Comment by jamesbrink** [comment]
@BrannonKing @qaisjp I have updated, patched and pushed the most recent build of this project. it is > 8GB :rofl:  enjoy

**Comment by qaisjp** [comment]
thanks boss
